modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
[[mods]]
modId = "footwork"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"
[[dependencies.footwork]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.footwork]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
